on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]

name: Build and test export

jobs:
  install:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
